### ISSUE TITLE
Project title is not ideal

### ISSUE THREAD

**Issue by cerisier** [joshleaves/licenjs#1]
Project title should be lice.js or licejs.

**Comment by moul** [comment]
:+1:

**Comment by moul** [comment]
:warning:

**Comment by moul** [comment]
:up:

**Comment by moul** [comment]
:dog:

**Comment by moul** [comment]
:balloon:

**Comment by joshleaves** [comment]
Sorry, I'm too busy working hard to add new licenses to this project to deal with such an important feature... I fear I will need to hire another developer to work on this full-time. Will you back my kickstarter?

**Comment by moul** [comment]
I will kick your back, is it a good starter ? :footprints: :back:

**Comment by cerisier** [comment]
:crocodile:
